#![cfg(shell = "pwsh")]

let thing = "test"

export let MEOW = "CAT"

pub rule meow {
    & "Write-Output hi"
    & ["Write-Output", "hi"]

    let cmd = "Write-Output"
    let mess = "hi"

    & cmd + " " + mess

    let mess = & "Write-Output hi"

    & [cmd, mess]
}